name: PR

on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Comment with Test Coverage
      uses: dkershner6/jest-coverage-commenter-action@v1
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        test_command: "npm run test:coverage"